[book]
title = "Helio 101"
description = "Helio sequencer reference manual"
authors = ["Peter Rudenko"]
multilingual = false
language = "en"
src = "."

[output.html]
git-repository-url = "https://github.com/helio-fm/helio-sequencer/tree/develop/Docs"
default-theme = "navy"
smart-punctuation = true

[output.html.playpen]
editable = false
runnable = false
copy-js = false
